// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpMheedpGr6n6hhQGYtcx0HLW09lQgdA',
    appId: '1:267622323375:web:d64a93e0dbc282fb6d305a',
    messagingSenderId: '267622323375',
    projectId: 'myfireflutter-5e6db',
    authDomain: 'myfireflutter-5e6db.firebaseapp.com',
    storageBucket: 'myfireflutter-5e6db.appspot.com',
    measurementId: 'G-CZL3CG651N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA13y5Cz3ewhebND7gApKTZ9wQR4Qxtp1E',
    appId: '1:267622323375:android:1b20d67db4cdc94c6d305a',
    messagingSenderId: '267622323375',
    projectId: 'myfireflutter-5e6db',
    storageBucket: 'myfireflutter-5e6db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oSMcPzziz_L4VXFEKjHy-Fk46fzOy40',
    appId: '1:267622323375:ios:d9449c98701e4e4a6d305a',
    messagingSenderId: '267622323375',
    projectId: 'myfireflutter-5e6db',
    storageBucket: 'myfireflutter-5e6db.appspot.com',
    iosClientId: '267622323375-a317qumu9fl4mpv46munn60tnm4soeu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydemosecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oSMcPzziz_L4VXFEKjHy-Fk46fzOy40',
    appId: '1:267622323375:ios:d9449c98701e4e4a6d305a',
    messagingSenderId: '267622323375',
    projectId: 'myfireflutter-5e6db',
    storageBucket: 'myfireflutter-5e6db.appspot.com',
    iosClientId: '267622323375-a317qumu9fl4mpv46munn60tnm4soeu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydemosecond',
  );
}
